services:
  react-pos:
    container_name: react-pos
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start